# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Etkinlik Tarihi'),
        ),
    ]
