# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20171225_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='Örnek', upload_to='', verbose_name='Etkinlik Resmi'),
        ),
    ]
