# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='Boş', upload_to='', verbose_name='Etkinlik Resmi'),
        ),
    ]
