# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20180122_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.FileField(default='Boş', upload_to='', verbose_name='Etkinlik Resmi'),
        ),
    ]
