# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20180122_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Sıra')),
                ('image', models.FileField(upload_to='product-additional-images', verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Görsel',
                'verbose_name_plural': 'Görseller',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='Boş', upload_to='', verbose_name='Etkinlik Resmi'),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.Activity', verbose_name='Görsel'),
        ),
    ]
