# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20180123_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='Boş', upload_to='', verbose_name='Etkinlik Resmi'),
        ),
    ]
