# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20180123_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='Boş', upload_to='', verbose_name='Etkinlik Resmi'),
        ),
    ]
