# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_remove_activity_imageadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Sıra')),
                ('image', models.FileField(upload_to='product-additional-images', verbose_name='Görsel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.Activity', verbose_name='Görsel')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'Görseller',
                'verbose_name': 'Görsel',
            },
        ),
    ]
