# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='event-activity-images', verbose_name='Görsel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.Activity', verbose_name='Etkinlik')),
            ],
            options={
                'verbose_name': 'Etkinlik faaliyeti',
                'verbose_name_plural': 'Etkinlik faaliyetleri',
                'ordering': ['event'],
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
