# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20180206_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventactivity',
            options={'ordering': ['event'], 'verbose_name': 'Etkinlik Resimleri', 'verbose_name_plural': 'Etkinlik Resimleri'},
        ),
        migrations.RemoveField(
            model_name='eventactivity',
            name='image',
        ),
    ]
