# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20180206_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event-activity-images', verbose_name='Görsel'),
        ),
    ]
