# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_eventactivity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventactivity',
            name='title',
        ),
    ]
