# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_remove_eventactivity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventactivity',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
    ]
