# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
                ('adress', models.TextField(default='Boğazkent Mah. 91.Sk. Kapı No:9/3 Serik/ANTALYA', verbose_name='Adres')),
                ('phone1', models.CharField(default='+90 541 722 13 75', max_length=225, verbose_name='Telefon 1')),
                ('phone2', models.CharField(default='+90 544 802 06 00', max_length=225, verbose_name='Telefon 2')),
                ('email', models.CharField(default='info@cocukcacim.org', max_length=225, verbose_name='E-posta')),
                ('facebook', models.CharField(default='https://www.facebook.com/cocukcacim', max_length=225, verbose_name='Facebook adresi')),
                ('twitter', models.CharField(default='https://twitter.com/cocukcacim', max_length=225, verbose_name='Twitter adresi')),
                ('instagram', models.CharField(default='https://www.instagram.com/cocukcacim/', max_length=225, verbose_name='İnstagram adresi')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim Detayları',
            },
        ),
    ]
