# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('name', models.CharField(default='Blok İsmi Giriniz!!!!', max_length=255, verbose_name='İsim')),
                ('title1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık 1')),
                ('title2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık 2')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Font Awesome Icon İsmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('image1', models.TextField(blank=True, null=True, verbose_name='Resim 1')),
                ('image2', models.TextField(blank=True, null=True, verbose_name='Resim 2')),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Bloklar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('name', models.CharField(max_length=255, verbose_name='Pozisyon İsmi')),
                ('position_name_slug', models.CharField(max_length=60, verbose_name='Pozisyon IDsi')),
            ],
            options={
                'verbose_name': 'Blok Pozisyonu',
                'verbose_name_plural': 'Blok Pozisyonları',
                'ordering': ['created_at'],
            },
        ),
    ]
