# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_block_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='title1',
            field=models.CharField(blank=True, default='Mavi Başlık', max_length=255, null=True, verbose_name='Başlık 1'),
        ),
        migrations.AlterField(
            model_name='block',
            name='title2',
            field=models.CharField(blank=True, default='Turuncu Başlık', max_length=255, null=True, verbose_name='Başlık 2'),
        ),
    ]
