# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whatwedo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
                ('text1bar', models.CharField(max_length=225, verbose_name='Ne yapıyoruz bar 1. kısım')),
                ('textbar1', models.TextField(verbose_name='Ne yapıyoruz bar 1. kısım içeriği')),
                ('text2bar', models.CharField(max_length=225, verbose_name='Ne yapıyoruz bar 2. kısım')),
                ('textbar2', models.TextField(verbose_name='Ne yapıyoruz bar 2. kısım içeriği')),
                ('text3bar', models.CharField(max_length=225, verbose_name='Ne yapıyoruz bar 3. kısım')),
                ('textbar3', models.TextField(verbose_name='Ne yapıyoruz bar 3. kısım içeriği')),
            ],
            options={
                'verbose_name': 'Ne yapıyoruz?',
                'verbose_name_plural': 'Ne yapıyoruz içeriği',
            },
        ),
        migrations.CreateModel(
            name='Whoarewe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
                ('image', models.ImageField(upload_to='', verbose_name='Biz kimiz? logo')),
                ('text', models.TextField(verbose_name='Biz kimiz? açıklama')),
            ],
            options={
                'verbose_name': 'Biz kimiz?',
                'verbose_name_plural': 'Biz kimiz içeriği',
            },
        ),
    ]
