# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managemembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
                ('member', models.CharField(max_length=225, verbose_name='Üye ismi')),
                ('member_appellation', models.CharField(max_length=225, verbose_name='Üye ünvanı')),
                ('member_bio', models.TextField(verbose_name='Üye özgeçmişi')),
                ('member_photo', models.ImageField(upload_to='', verbose_name='Üye fotoğrafı')),
            ],
            options={
                'verbose_name_plural': 'Yönetim Kurulu',
                'verbose_name': 'üye',
            },
        ),
    ]
